---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    project: chat
spec:
  endpoints:
  - honorLabels: true
  # matches endpoint prometheus-operated port
    port: web
  selector:
    matchLabels:
     # matches endpoint prometheus-operated label
     # kubectl describe endpoints prometheus-operated -n monitoring
      operated-prometheus: "true"
