---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: cadvisor
  labels:
    project: chat
spec:
  selector:
    matchLabels:
      name: cadvisor
  endpoints:
  - port: http