---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: demo
  namespace: monitoring
spec:
  version: v0.21.0
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
