---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: monitoring
  labels:
    project: chat
spec:
  endpoints:
  - honorLabels: true
    port: ui
  selector:
    matchLabels:
      # match service label
      # kubectl describe endpoints grafana -n monitoring
      app: grafana
