apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    # for discovery by prometheus
    project: chat
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: 0.72.0
  name: prometheus-operator
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
   # matches endpoint prometheus-operate port
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
       # matches endpoint prometheus-operated label
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/version: 0.72.0
